name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
#       - name: configure
#       run: rm -rf build && mkdir build cd build && cmake ../
    - name: configure
      run: cd build && cmake ../
    - name: make
      run: cd build && make
    - name: make check
      run: cd build && ./test
#     - name: make distcheck
#       run: make distcheck
